apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  # Use the sds profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: sds
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      # Enable mutual TLS for the control plane
      controlPlaneSecurityEnabled: true
      mtls:
        # Require all service to service communication to have mtls
        enabled: true
        auto: true
      proxy:
        # Enable istio-proxy (i.e. envoy) access log and send it to stdout
        accessLogFile: "/dev/stdout"
        # Add delay to the Readiness probe of istio-proxy
        readinessInitialDelaySeconds: 5
    sidecarInjectorWebhook:
      # Needed so probes can work properly with mTLS
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        # Exposes Istio ingress-gateway as an Azure ILB  
        serviceAnnotations:
          "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
        # Gets real source IP (If using DNAT through Azure firewall it would be the firewall IP which Azure will hopefully fix)
        externalTrafficPolicy: Local
        # Enable SDS for the ingress gateway to handle TLS certs as k8s secrets
        sds:
          enabled: true
    grafana:
      # Enable Grafana deployment for analytics and monitoring dashboards
      enabled: true
      security:
        # Enable authentication for Grafana
        enabled: true
    kiali:
      # Enable the Kiali deployment for a service mesh observability dashboard
      enabled: true
    tracing:
      # Enable the Jaeger deployment for tracing
      enabled: true
  # Enable nodeagent to mount certificates through secrets
  security:
    components:
      nodeAgent:
        enabled: true
